---
title: "Summers 2018-2019 Milkweed Analysis- TRYING OUT HAVERSINE FORMULA AGAIN."
author: "Sophie Breitbart"
date: "10/31/2019"
output:
  html_document:
    number_sections: true
    df_print: paged
    toc: yes
    toc_depth: 6
    toc_float:
      collapsed: yes
  pdf_document:
    toc: yes
    toc_depth: '2'
editor_options: 
  chunk_output_type: console
---

# Set up notebook
## Install, load packages
```{r message=FALSE, warning=FALSE}
# install.packages("tibble")
# install.packages("dplyr")
# install.packages("swirl")
# install.packages("digest", type="source")
# install_github("vqv/ggbiplot")
# install.packages(c("slidify", "ggplot2", "devtools"))
# install.packages("ggiraphExtra")
# install.packages('backports')
# install.packages('rmarkdown')
# install.packages("lme4")
# install.packages("lmerTest")
# install.packages("tidyverse")
# install.packages("vegan")
# install.packages("car")
# install.packages("psych")
# install.packages("cowplot")
# install.packages("RcppEigen")
# install.packages("flextable")
# install.packages("mnormt")
# install.packages("BH")
# install.packages("plogr")
# install.packages("ggpubr")
# install.packages("rpart")
# install.packages("ISLR")
# install.packages("lindia")
# devtools::install_github("hadley/devtools")
# devtools::install_github("cardiomoon/ggiraphExtra")
# devtools::install_github("dkahle/ggmap")
# install.packages('maps')
# install.packages("ggspatial")
# install.packages("ggsn")
# install.packages("GISTools")
# install.packages("janitor")
# install.packages("agricolae")
# install.packages("geosphere")
library(geosphere)
library(ggspatial)
library(ggmap)
library(agricolae)
library(janitor)
library(ggsn)
library(GISTools)
library(devtools)
library(hrbrthemes)
library(dplyr)
library(tidyr)
library(viridis)
library(rpart)
library(flextable)
library("tibble", lib.loc="~/R/win-library/3.5")
library(ISLR)
library(MASS)
library(car)
library(data.table)
library(plyr)
library(gridExtra)
library(Hmisc)
library(lme4)
library(nlme)
library(reshape2)
library(lmerTest)
library(tidyverse)
library(vegan)
library(lindia)
library(e1071)
library(ggpubr)
library(forcats)
library(car)
library(multcomp)
library(lsmeans)
library(ggbiplot)
require(MASS)
require(scales)
require(ggplot2)
require(ggiraph)
require(ggiraphExtra)
```

## Import data
```{r, import}
all_data <- read.csv("~/R_Projects/SummerMilkweed19Data/Transect_Milkweed_Data_Combined_w_Haversine_2018_and_2019_endofseason.csv",  header=T, na.strings=c("","NA"))

```

## Clean data file
```{r message=FALSE, warning=FALSE}

# Neaten first column's name
colnames(all_data)[1] <- "Year"

# Replace x's (which denote no data) with NA
all_data[all_data == "x"] <- NA

# # Convert appropriate column types to character and then numeric.
# to_char_num <- c(5:14, 21:23,25,28:29,31,33:54, 56)
# data2[to_char_num] <- lapply(data2[to_char_num], as.character)
# data2[to_char_num] <- lapply(data2[to_char_num], as.numeric)
# 
# # Convert appropriate column types to integer.
# to_int <- c(1,18,24,30:32,55)
# data2[to_int] <- lapply(data2[to_int], as.integer)

# just taking pertinent columns
data2 <- all_data[,c(1:3, 21:22, 25)]
data2$Ref_Lat <- "43.656327"
data2$Ref_Long <- "-79.380904"
data2$Latitude <- as.numeric(as.character(data2$Latitude))
data2$Longitude <- as.numeric(as.character(data2$Longitude))
data2$Ref_Lat <- as.numeric(as.character(data2$Ref_Lat))
data2$Ref_Long <- as.numeric(as.character(data2$Ref_Long))


test2 <- data2 %>% mutate(CTD_m = distHaversine(cbind(Longitude, Latitude), cbind(Ref_Long, Ref_Lat)))
test2$CTD_km <- test2$CTD / 1000

# latlongs <- data2[,c(4:5)]
# latlongs$Latitude <- as.numeric(as.character(latlongs$Latitude))
# latlongs$Longitude <- as.numeric(as.character(latlongs$Longitude))
# 
# 
# Refs <- data.frame("43.656327", "-79.380904")
# colnames(Refs)[1] <- 'Ref_Lat'
# colnames(Refs)[2] <- 'Ref_Long'
# Refs$Ref_Lat <- as.numeric(as.character(Refs$Ref_Lat))
# Refs$Ref_Long <- as.numeric(as.character(Refs$Ref_Long))
# 
# idk <-latlongs %>% rowwise() %>% mutate(newcolumn_distance = distHaversine(c(latlongs$Longitude, latlongs$Latitude), c(Refs$Ref_Long, Refs$Ref_Lat)))
# 
# 
# 
# test1 <- latlongs %>% mutate(CTD = distHaversine(cbind(Longitude, Latitude), cbind(Ref_Long, Ref_Lat)))



# idk <- geosphere::distm(latlongs[,c('Longitude','Latitude')], latlongs[,c('Ref_Long','Ref_Lat')], fun=distVincentyEllipsoid)


```

