with(Ave_Pollinator_New, boxplot(split(leaf.cutter.bees..Megachile.sp.., Type), col = c("Blue", "Red"), ylab = "Average Abundance of Megachile sp. per Site", xlab = "Site Classification"))
with(Ave_Pollinator_New, boxplot(split(sweat.bees..Halictidae.sp.., Type), col = c("Blue", "Red"), ylab = "Average Abundance of Halictidae sp. per Site", xlab = "Site Classification"))
with(Ave_Pollinator_New, boxplot(split(orange.beetle..Rhagoycha.fulva., Type), col = c("Blue", "Red"), ylab = "Average Abundance of Rhagoycha fulva per Site", xlab = "Site Classification"))
with(Ave_Pollinator_New, boxplot(split(`apis melifera`, Type), col = c("Blue", "Red"), ylab = "Average Abundance of Apis mellifera per Site", xlab = "Site Classification"))

with(Ave_Pollinator_Data, wilcox.test(`leaf cutter bees (Megachile sp.)`~Type, paired = FALSE, alternative = "less"))
with(Ave_Pollinator_Data, wilcox.test(`orange beetle (Rhagoycha fulva)`~Type, paired = FALSE, alternative = "greater"))
with(Ave_Pollinator_Data, wilcox.test(`sweat bees (Halictidae sp.)`~Type, paired = FALSE, alternative = "two.sided"))
with(Ave_Pollinator_New, wilcox.test(`apis melifera`~Type, paired = FALSE, alternative = "greater"))

with(Ave_Pollinator_New, wilcox.test(flowering~Type, paired = FALSE))
with(Ave_Pollinator_New, boxplot(split(flowering, Type), col = c("Blue", "Red"), ylab = "Average Number of Inflorecence per Plant", xlab = "Site Classification"))

with(Ave_Pollinator_Data, boxplot(split(`diversity all groups (bee families + other spp.)`, Type), col = c("Blue", "Red"), xlab = "Site Classification", ylab = "Average Pollinator Diversity"))
with(Ave_Pollinator_New, boxplot(split(abundance.all.sp., Type), col = c("Blue", "Red"), xlab = "Site Classification", ylab = "Average Pollinator Abundance"))

with(Ave_Pollinator_Data, wilcox.test(`diversity all groups (bee families + other spp.)` ~ Type, paired = FALSE))
with(Ave_Pollinator_Data, wilcox.test(`abundance all sp.` ~ Type, paired = FALSE, alternative = "greater"))

with(Ave_Pollinator_Data, cor.test(`DistanceFromCityCenter (KM)`, log_pol_abundance))
with(Ave_Pollinator_Data, cor.test(`DistanceFromCityCenter (KM)`, log_pol_diversity))

log_pollinator_abundance_lm <- lm(`DistanceFromCityCenter (KM)` ~ log_pol_abundance, data = Ave_Pollinator_Data)
print(log_pollinator_abundance_lm)
summary(log_pollinator_abundance_lm)
plot(log_pollinator_abundance_lm)
with(Ave_Pollinator_Data, cor.test(`DistanceFromCityCenter (KM)`, log_pol_abundance))
with(Ave_Pollinator_Data, cor.test(`DistanceFromCityCenter (KM)`, `abundance all sp.`))
with(Ave_Pollinator_Data, plot(`DistanceFromCityCenter (KM)`, log_pol_abundance, col = "blue", pch = 16, xlab = "Distance from City Center (km)", ylab = "Average Pollinator Abundance (log)"))
par(new = TRUE)
abline(lm(log_pol_abundance ~ `DistanceFromCityCenter (KM)`, data = Ave_Pollinator_Data), col = "red")
par(new = FALSE)

log_pollinator_diversity_lm <- lm(`DistanceFromCityCenter (KM)` ~ log_pol_diversity, data = Ave_Pollinator_Data)
print(log_pollinator_diversity_lm)
summary(log_pollinator_diversity_lm)
plot(log_pollinator_diversity_lm)
with(Ave_Pollinator_Data, cor.test(`DistanceFromCityCenter (KM)`, log_pol_diversity))
with(Ave_Pollinator_Data, cor.test(`DistanceFromCityCenter (KM)`, `diversity all groups (bee families + other spp.)`))
with(Ave_Pollinator_Data, plot(`DistanceFromCityCenter (KM)`, log_pol_diversity, col = "blue", pch = 16, xlab = "Distance from City Center (km)", ylab = "Average Pollinator Diversity (log)"))
par(new = TRUE)
abline(lm(log_pol_diversity ~ `DistanceFromCityCenter (KM)`, data = Ave_Pollinator_Data), col = "red")
par(new = FALSE)
