
# -------------------
# Load packages
#-------------------
library(dplyr)
library(here)
library(stringi)



#-------------------
# Import data
#-------------------
Transect_Data <- read.csv(here::here("./raw_data/Transect_Milkweed_Data_2018_and_2019_endofseason.csv"),
header = T,
na.strings=c("","NA")) %>%
  as.data.frame()


#-------------------
# Clean all data
#-------------------



## Add City_dist values with Haversine formula
#----------------------------------------

# Ref lat and longs are for Yonge & Dundas intersection in downtown Toronto
Transect_Data$Ref_Lat <- "43.656327"
Transect_Data$Ref_Long <- "-79.380904"

# Make lat/long cols numeric
Transect_Data$Latitude <- as.numeric(as.character(Transect_Data$Latitude))
Transect_Data$Longitude <- as.numeric(as.character(Transect_Data$Longitude))
Transect_Data$Ref_Lat <- as.numeric(as.character(Transect_Data$Ref_Lat))
Transect_Data$Ref_Long <- as.numeric(as.character(Transect_Data$Ref_Long))

# Find distances from Yonge/Dundas to sample sites (in meters)
Transect_Data <- Transect_Data %>% mutate(CTD_m = distHaversine(cbind(Longitude, Latitude), cbind(Ref_Long, Ref_Lat)))

# conver to km
Transect_Data$City_dist <- Transect_Data$CTD / 1000

# drop ref lat, long, and city_dist (in m) cols
Transect_Data <- Transect_Data[,-c(39:41)]



## More cleaning
#----------------------------------------

# Other_pod_lengths column has all pod lengths for one plant, separated by commas. This line of code separates them into their own columns. Ex. first pod length goes into "OPodL1", etc.
# The plant with the most pods had 21 (including the collected pod, which has its own category ("Collected_pod_length"), so there should be one less than 21 columns for the remaining pod's lengths: 20 columns in total.)
Transect_Data_18_19 <- NULL
Transect_Data_18_19 <- separate(Transect_Data, Other_pod_lengths, into = c("OPodL1", "OPodL2", "OPodL3", "OPodL4", "OPodL5", "OPodL6", "OPodL7", "OPodL8", "OPodL9", "OPodL10", "OPodL11", "OPodL12", "OPodL13", "OPodL14", "OPodL15", "OPodL16", "OPodL17", "OPodL18", "OPodL19", "OPodL20"), sep = ",")

# Neaten first column's name
colnames(Transect_Data_18_19)[1] <- "Year"

# Replace x's (which denote no data) with NA
Transect_Data_18_19[Transect_Data_18_19 == "x"] <- NA

# Convert appropriate column types to character and then numeric.
to_char_num <- c(5:14, 21:23,25,28:29,31,33:54, 56)
Transect_Data_18_19[to_char_num] <- lapply(Transect_Data_18_19[to_char_num], as.character)
Transect_Data_18_19[to_char_num] <- lapply(Transect_Data_18_19[to_char_num], as.numeric)

# Convert appropriate column types to integer.
to_int <- c(1,18,24,30:32,55)
Transect_Data_18_19[to_int] <- lapply(Transect_Data_18_19[to_int], as.integer)

# check column types are correct
colnames(Transect_Data_18_19)[14] <- "Height_July"
colnames(Transect_Data_18_19)[28] <- "Height_Sept"

# str(Transect_Data_18_19)

# Export csv of pop IDs and city distances
Transect_Data_18_19[,c("Pop_ID", "City_dist", "Transect_ID")] %>%
  group_by(Pop_ID) %>%
  dplyr::summarise(
    City_dist=first(City_dist),
    Transect_ID=first(Transect_ID)) %>%
  write.csv(., here::here("./Chapter1/clean_data/Sites_distances.csv"))




## Add average pollen removal and pod length columns
#----------------------------------------

## Add "Average Pollinia" column to main dataset and move it after other pollinia columns
# Add new column for average pollinia removal per plant per year
Transect_Data_18_19$Average_Pollinia <- NA

# Move this new column after columns for pollinia removed per flower
Transect_Data_18_19 = Transect_Data_18_19[, c(1:13, 58, 14:57)]

# Make the column numeric
Transect_Data_18_19$Average_Pollinia <- as.numeric(as.character(Transect_Data_18_19$Average_Pollinia))

# Calculate average pollinia removed. Missing flowers excluded from calculation. Ex. the average pollinia removed for a plant with 9 "readable" flowers are averaged over 9. If the plant only had 3 "readable" flowers, the mean is averaged over 3.
Transect_Data_18_19[14] <- rowMeans(Transect_Data_18_19[,5:13], na.rm = TRUE)




## Adding average pod length column (only applies to data collected in 2019; pod lengths were not measured in 2018.)

Transect_Data_18_19$Average_pod_length <- NA
Transect_Data_18_19$Average_pod_length <- rowMeans(Transect_Data_18_19[,35:54], na.rm = TRUE)
# write.csv(Transect_Data_18_19,'Transect_Data_18_19_avgpodlengths.csv')





## Make summary table showing average values per population
#-------------------------------------------------------------

# make summary table for several variables PER POPULATION
AvgVars_byPatch <- Transect_Data_18_19[,c("Patch_ID","Average_Pollinia", "City_dist", "Transect_ID", "Year", "Height_July", "Area_sq_m_2018", "Plants_present_2018", "Height_Sept", "Viable_Pods", "Total_Pods", "Peduncles", "Average_pod_length")] %>% group_by(Patch_ID, Year) %>%
    dplyr::summarise(
      Average_Pollinia=mean(Average_Pollinia,na.rm = TRUE),
      City_dist=mean(City_dist),
      Transect_ID=first(Transect_ID),
      Peduncles=mean(Peduncles,na.rm = TRUE),
      Height_July=mean(Height_July,na.rm = TRUE),
      Area_sqm_18=first(Area_sq_m_2018,na.rm = TRUE),
      Plants_present_2018=mean(Plants_present_2018,na.rm=TRUE),
      Height_Sept=mean(Height_Sept,na.rm = TRUE),
      Viable_Pods=mean(Viable_Pods,na.rm = TRUE),
      Total_Pods=mean(Total_Pods,na.rm = TRUE),
      nPlants=n(),
      Average_pod_length=mean(Average_pod_length, na.rm=TRUE)
      )
# Check column types are correct
# str(AvgVars_byPatch)

# Neaten first column's name
AvgVars_byPatch$Year <- as.factor(AvgVars_byPatch$Year)

# Find plant density per site
AvgVars_byPatch$density_sqm_18 <- AvgVars_byPatch$Area_sqm_18 / AvgVars_byPatch$Plants_present_2018

# Create 2 other data frames: One for only 2018 data, the other with only 2019 data
AvgVars_byPatch_2018 <- AvgVars_byPatch[which(AvgVars_byPatch$Year == "2018"), ]
AvgVars_byPatch_2019 <- AvgVars_byPatch[which(AvgVars_byPatch$Year == "2019"), ]



## Making new table that doesn't have an average pollinia row: each flower is own row
#----------------------------------------------------------------------------
# make table wide to long so each flower has own row
long_Transect_Data_18_19 <- gather(Transect_Data_18_19, Inflor_flower, Pollinia_removed, Pollinia_1_1:Pollinia_3_3, factor_key=TRUE)

# remove "Pollinia_" from Flower column
long_Transect_Data_18_19$Inflor = substr(long_Transect_Data_18_19$Inflor_flower,10,10)
long_Transect_Data_18_19$Flower = substr(long_Transect_Data_18_19$Inflor_flower,12,12)

# remove "Inflor_flower" column
long_Transect_Data_18_19 <- subset(long_Transect_Data_18_19, select = -c(Inflor_flower))

# Make the 3 new columns numeric
long_Transect_Data_18_19$Inflor <- as.numeric(as.character(long_Transect_Data_18_19$Inflor))
long_Transect_Data_18_19$Pollinia_removed <- as.numeric(as.character(long_Transect_Data_18_19$Pollinia_removed))
long_Transect_Data_18_19$Flower <- as.numeric(as.character(long_Transect_Data_18_19$Flower))

# reorder columns so new cols are near beginning of df
long_Transect_Data_18_19 <- long_Transect_Data_18_19[,c(1:4, 50:53, 49, 5:48)]

# make patch ID, plant, and inflor cols factors
long_Transect_Data_18_19$Patch_ID <- as.factor(as.character(long_Transect_Data_18_19$Patch_ID))
long_Transect_Data_18_19$Plant_Num <- as.factor(as.character(long_Transect_Data_18_19$Plant_Num))
long_Transect_Data_18_19$Inflor <- as.factor(as.character(long_Transect_Data_18_19$Inflor))

# make pollinia removed an integer
long_Transect_Data_18_19$Pollinia_removed <- as.integer(as.character(long_Transect_Data_18_19$Pollinia_removed))

# separate 2018-2019
long_Transect_Data_18 <- filter(long_Transect_Data_18_19, Year == "2018")
long_Transect_Data_19 <- filter(long_Transect_Data_18_19, Year == "2019")



## SummarySE
#------------------

## summary of pollinia removed per inflorescence
long_summary_inflor <- summarySE(long_Transect_Data_18_19,
                          measurevar= 'Pollinia_removed',
                          groupvars = c('Year', 'Patch_ID', 'City_dist', 'Transect_ID', 'Plant_Num', 'Inflor'))

## summary of pollinia removed per plant
long_summary_plant <- summarySE(long_Transect_Data_18_19,
                          measurevar= 'Pollinia_removed',
                          groupvars = c('Year', 'Patch_ID', 'City_dist', 'Transect_ID', 'Plant_Num'))

## summary of pollinia removed per pop
long_summary_pop <- summarySE(long_Transect_Data_18_19,
                          measurevar= 'Pollinia_removed',
                          groupvars = c('Year', 'Patch_ID', 'City_dist', 'Transect_ID'))

### change column "n" to "flowers_read"
names(long_summary_pop)[5] <- "Flowers_read"

### remove rows w/NAs
long_sum <- long_summary_pop %>% filter(!is.na(Pollinia_removed))



## Adjusting long table from previous chunk for pods/peds analyses (removing sterile pops)
### Remove sterile populations
#### For population-level table

# First, find populations that are "sterile"- no plants w/pods or flowers per year
No_flowers <- AvgVars_byPatch[is.na(AvgVars_byPatch$Average_Pollinia) & (is.na(AvgVars_byPatch$Total_Pods) | (AvgVars_byPatch$Total_Pods == 0)),]

# Then, remove if population only has 1 year's records in this df (i.e. it was only "sterile" for one year)
## sterile_pops_bothyears only includes rows with the 2019 data from the sterile populations, but it was essential for making the list version of this dataframe's Patch_ID row (next line)
sterile_pops_bothyears <- No_flowers[duplicated(No_flowers[c("Patch_ID")]),]
sterile_pops_bothyears_list <- sterile_pops_bothyears$Patch_ID

# Populations that were sterile for any given year
sterile_pops_18 <- No_flowers[which(No_flowers$Year == "2018"),]
sterile_pops_19 <- No_flowers[which(No_flowers$Year == "2019"),]

# New dataframe with all records for fertile populations (i.e. all populations - sterile)
fertile_pops_all <- AvgVars_byPatch %>% 
  filter(!Patch_ID %in% sterile_pops_bothyears_list)


# check that fertile_pops_all has no populations in common with sterile_pops_bothyears
overlap_check <- inner_join(sterile_pops_bothyears, fertile_pops_all)
# this new df is empty = confirmed exclusivity of sterile and fertile dataframes.


# Populations that were fertile for any given year
fertile_pops_18 <- fertile_pops_all[which(fertile_pops_all$Year == "2018"),]
fertile_pops_19 <- fertile_pops_all[which(fertile_pops_all$Year == "2019"),]




#### For flower-level table
# remove rows with cells that match both the year and population of sterile pops list
sterile_list <- as.list(sterile_pops_bothyears %>% dplyr::select(Patch_ID))

## THIS LISTS EACH ROW AS A FLOWER... BE CAREFUL
fertile_long <- subset(long_Transect_Data_18_19,
                       long_Transect_Data_18_19$Patch_ID != sterile_list)

# separate 2018-2019
fertile_long_18 <- filter(fertile_long, Year == "2018")
fertile_long_19 <- filter(fertile_long, Year == "2019")


fertile <- anti_join(Transect_Data_18_19, sterile_pops_bothyears, by = "Patch_ID")
fertile_urban <- fertile %>% filter(Transect_ID != 'Rural')


## Dataframes excluding "empty" populations (for pollen removal dataset, pops w/o any flowers... for follicle dataset, pops w/o any follicles... etc.)
#--------------------------------------------------------------------------

# Make new data frames of 2018 & 2019 pollinia removal data that excludes empty pops
AvgVars_notNA_Poll_18 <- AvgVars_byPatch_2018[!is.na(AvgVars_byPatch_2018$Average_Pollinia),]
AvgVars_notNA_Poll_19 <- AvgVars_byPatch_2019[!is.na(AvgVars_byPatch_2019$Average_Pollinia),]

# Make new data frames of 2018 & 2019 follicle data that excludes pops w/o any pods
AvgVars_notNA_Pod_18 <- fertile_pops_18[!is.na(fertile_pops_18$Total_Pods),]
AvgVars_notNA_Pod_19 <- fertile_pops_19[!is.na(fertile_pops_19$Total_Pods),]

# Make new data frames of 2018 & 2019 peduncle data that excludes pops without any pods
AvgVars_notNA_Ped_18 <- fertile_pops_18[!is.na(fertile_pops_18$Peduncles),]
AvgVars_notNA_Ped_19 <- fertile_pops_19[!is.na(fertile_pops_19$Peduncles),]





#-------------------------------------------------------------
## Add dataframe with urbanization scores, add to existing dfs
#-------------------------------------------------------------

# Import urb_index values for each of these rows
urb_scores <- read.csv(here("./Figures_Tables/UrbanizationScore/Urbanization_Scores_Table.csv"),  header=T, na.strings=c("","NA"))

Pops_patches_all <- Transect_Data[,c(2,3)] %>% dplyr::distinct()
Pops_patches <- Pops_patches_all %>% group_by(Patch_ID) %>%
  dplyr::summarise(
    Pop_ID = first(Pop_ID))

urb_scores <- dplyr::inner_join(urb_scores, Pops_patches, by = "Pop_ID") %>% dplyr::select(., -Patch_ID.y) %>% dplyr::rename(., Patch_ID = Patch_ID.x)


#===============================================================#
#                            (g)lm datasets                     #
#===============================================================#

## Pollen removal------------------------
### gradient
urb_scores_poll_all <- dplyr::left_join(AvgVars_notNA_Poll_18_19, urb_scores, by = "Patch_ID")
### urban subs
urb_scores_poll <- dplyr::left_join(AvgVars_notNA_Poll_18_19_urban, urb_scores, by = "Patch_ID")

## Pods------------------------
### gradient
urb_scores_pods_all <- dplyr::left_join(fertile_pops_all_notNApods, urb_scores, by = "Patch_ID")
### urban subs
urb_scores_pods <- dplyr::left_join(fertile_pops_all_notNApods_urban, urb_scores, by = "Patch_ID")


## Peduncles------------------------
### gradient
urb_scores_peds_all <- dplyr::left_join(fertile_pops_all_notNApeds, urb_scores, by = "Patch_ID")

### urban subs
urb_scores_peds <- dplyr::left_join(fertile_pops_all_notNApeds_urban, urb_scores, by = "Patch_ID")


## Height------------------------
### gradient
urb_scores_height_all <- dplyr::left_join(fertile_pops_all_height_18_19_sept, urb_scores, by = "Patch_ID")

### urban subs
urb_scores_height <- dplyr::left_join(fertile_pops_all_height_18_19_urban_sept, urb_scores, by = "Patch_ID")


## Pods/ped------------------------
### gradient
urb_scores_podperped_all <- dplyr::left_join(fertile_pops_all_podsperped, urb_scores, by = "Patch_ID")

### urban subs
urb_scores_podperped <- dplyr::left_join(fertile_pops_all_podsperped_urban, urb_scores, by = "Patch_ID")


#===============================================================#
#                            (g)lmer datasets                   #
#===============================================================#

# Pollen removal------------------------
### gradient
urb_scores_poll_long <- dplyr::left_join(long_Transect_Data_18_19, urb_scores, by = "Patch_ID")

### urban subs
urb_scores_poll_all_long <- dplyr::left_join(long_urban, urb_scores, by = "Patch_ID")

## Pods------------------------
### gradient
fertile_pops_all_notNApods <- fertile_pops_all[!is.na(fertile_pops_all$Viable_Pods),]
urb_scores_pods_long <- dplyr::left_join(fertile, urb_scores, by = "Patch_ID")

### urban subs
urb_scores_pods_all_long <- dplyr::left_join(fertile_urban, urb_scores, by = "Patch_ID")


## Peduncles------------------------
### gradient
urb_scores_peds_long <- dplyr::left_join(fertile, urb_scores, by = "Patch_ID")

### urban subs
urb_scores_peds_all_long <- dplyr::left_join(fertile_urban, urb_scores, by = "Patch_ID")


## Height------------------------
### gradient
urb_scores_height_long <- dplyr::left_join(fertile, urb_scores, by = "Patch_ID")

### urban subs
urb_scores_height_all_long <- dplyr::left_join(fertile_urban, urb_scores, by = "Patch_ID")


## Pods/ped------------------------
### gradient
urb_scores_podsperped_long <- dplyr::left_join(fertile, urb_scores, by = "Patch_ID")

### urban subs
urb_scores_podsperped_all_long <- dplyr::left_join(fertile_urban, urb_scores, by = "Patch_ID")






#-------------------
# Export to new csv
#-------------------
write.csv(DC_all_2019,
          here::here("./CommonGardenExperiment_2019Data/clean_data/clean_data_2019KSR.csv"))
